# version: '3.8'

services:
  nestjs_api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
      - NODE_ENV=development
    volumes:
      - ./src:/app/src
    networks:
      - nesttodo
    depends_on:
      - mysql_db

  mysql_db:
    image: mysql:8.0
    ports:
      - '3306:3306' # Use the default MySQL port
    environment:
      - MYSQL_ROOT_PASSWORD=root_password_123
      - MYSQL_DATABASE=nesttodo_be_dev
      - MYSQL_USER=testuser
      - MYSQL_PASSWORD=testuser123
    networks:
      - nesttodo

networks:
  nesttodo:
    driver: bridge
